name: riverpod_scalable_app
description: "This template demonstrates Firebase Authentication and Firestore CRUD operations within a scalable Flutter app structure using Riverpod"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^2.14.0
  firebase_auth: ^4.10.1
  cloud_firestore: ^4.11.1
  flutter_riverpod: ^2.5.1
  go_router: ^14.6.2
  shared_preferences: ^2.3.4
  localization:
    path: packages/localization
  preferences:
    path: packages/preferences


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true

